### ISSUE TITLE
ctrl+enter and shift+enter do not work on linux

### ISSUE THREAD

**Issue by webczat** [waf/CSharpRepl#111]
Hi,
ctrl+enter and shift+enter keys don't work on linux and an alternative would be kinda useful.
Note from what I know, this is not a dotnet bug, as linux generally sends enter, ctrl+enter and shift+enter the same way. at least this is the case on my terminal emulator.

**Comment by kindermannhubert** [comment]
Hi, I'm not Linux user, so I don't have experience with it, but when i try simplest repro:
`var key = Console.ReadKey();`
and press `Control+Enter`
on Windows I get:
![image](https://user-images.githubusercontent.com/11704036/160292495-035191d2-9e74-48cc-bc34-9f0b18912883.png)

and on Linux (Ubuntu) the key modifiers are empty:
![image](https://user-images.githubusercontent.com/11704036/160292572-e548644e-1fdd-46e8-821b-4cbda12f8ebd.png)

so we just don't see the Control modifier.

From this, it looks to me like a bug in .NET.

In the new release of CSharpRepl, you will be able to set up custom keybindings for this (#67, #73).

**Comment by waf** [comment]
Also see https://github.com/dotnet/runtime/issues/802, scheduled for .NET 7.

**Comment by kindermannhubert** [comment]
In any case, we can't do anything about it -  it will be solved or not in .NET 7. Not the solution is to use different key bindings.
Configurable key bindings are done but not released yet.
I'm closing this issue with it.
