### ISSUE TITLE
New line is inserted instead of completion item commit (only in some cases)

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#120]
With:
`--newLineKeys Enter --submitPromptKeys Ctrl+Enter --submitPromptDetailedKeys Ctrl+Shift+Enter --submitPromptDetailedKeys Ctrl+Alt+Enter`

Write:
`class c : `
trigger completion window and press Enter.

**Comment by kindermannhubert** [comment]
This should be fixed by https://github.com/waf/PrettyPrompt/issues/185.

**Comment by waf** [comment]
Confirmed that this is resolved when we upgraded PrettyPrompt to get that fix (upgraded in https://github.com/waf/CSharpRepl/pull/136)
