### ISSUE TITLE
Help command result has to be dynamic

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#124]
### Version

last

### What happened?

There are hardcoded key bindings:
![image](https://user-images.githubusercontent.com/11704036/161324988-5a46c0c6-e1cc-4fb9-9819-46c19e68f7de.png)

but they are configurable.

**Comment by Keyros** [comment]
Hi!
PR: https://github.com/waf/CSharpRepl/pull/289 merged
should this bug be closed?

**Comment by waf** [comment]
Yes, thanks for implementing it! Feel free to close it.

**Comment by Keyros** [comment]
> Yes, thanks for implementing it! Feel free to close it.

I can't close it apparently due to permissions
