### ISSUE TITLE
Implement into Existing app for as a Library runtime REPL

### ISSUE THREAD

**Issue by CallumCarmicheal** [waf/CSharpRepl#127]
### Feature Description

Not sure if this has been discussed or asked before, Looked around the issues and could not find one relevant. If there is, Sorry I must've missed it.

I currently work inside a CMS that is based on WinForms and .Net 4.5, All of the custom code is stored in a database and compiled at runtime which makes it a slow and painful task to quickly test and develop solutions in the software.

Is there any possibility to embed CSharpRepl as a library and open it in the current process with access to the runtime to allow for real time debugging?

**Comment by kindermannhubert** [comment]
Hi, it was discussed in #57 and #100. 
I assume your main problem will be .NET Framework 4.5. CSharpRepl is .NET 6 application.

**Comment by CallumCarmicheal** [comment]
Thank you for the help @kindermannhubert, I missed those comments even after looking :X.

Yeah that was what I was looking for, Sadly you are correct about the .Net 6 though. I have to find another solution to work with 3.5.
