### ISSUE TITLE
Referencing dll in csx file

### ISSUE THREAD

**Issue by realivanjx** [waf/CSharpRepl#13]
So i have built a dll using net5 that contains classes and stuff i needed. The question is how to reference it into my .csx file? I tried this:
`#r "../xu-cell-pos.Server/bin/Debug/net5.0/xu-cell-pos.Server.dll"`
But it gave me an error:
`(3,1): error CS0006: Metadata file '../xu-cell-pos.Server/bin/Debug/net5.0/xu-cell-pos.Server.dll' could not be found`
I made sure the relative file path are correct. Also this works on dotnet-script. Thanks.

**Comment by waf** [comment]
Yes, it looks like this does not accept relative paths -- you'd need to provide an absolute path for now (that does work for you, right?). That's definitely something we should support though. Should be a quick fix to our MetadataReferenceResolver implementation.

**Comment by realivanjx** [comment]
I havent tested absolute path yet but i will later and report back to you. Thanks.

**Comment by waf** [comment]
I've released version csharprepl 0.2.3 that adds support for relative paths, thanks for reporting it! I'm going to close this, but feel free to re-open if you're still seeing issues.
