### ISSUE TITLE
Annoying completion while writing lambda args

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#145]
### Version

latest

### What happened?

E.g. when writing following:
`"".Where(c => c == 'x')`

After writing space after the first `c` the `char` is completed so we have
`"".Where(char `

In VS completion list is triggered for lambda args too but no completion item is selected while writing (can be explicitly selected e.g. by up/down arrow).

**Comment by waf** [comment]
Sounds similar to what was (supposedly) fixed in https://github.com/waf/CSharpRepl/pull/137

**Comment by kindermannhubert** [comment]
The test is passing but real usage does not.

**Comment by kindermannhubert** [comment]
The issue was fixed for
`"".Where(c => c == 'x')`
but not for
`"".Where(c=> c == 'x')`
