### ISSUE TITLE
Completion interferes when typing anonymous object initializers

### ISSUE THREAD

**Issue by waf** [waf/CSharpRepl#157]
### Version

current main branch

### What happened?

It's very hard to type Anonymous Object initializers, as the completion window will open when typing the property name, and pressing space will commit the first suggestion.

For example, trying to type `new { i = 0 }` (ignoring the completion window) will result in `new { int= 0 }` because `int` is autoinserted for `i` and committed when <kbd>Spacebar</kbd> is pressed.

**Comment by waf** [comment]
Originally we tried to fix this via https://github.com/waf/CSharpRepl/pull/137, but ended up reverting it in https://github.com/waf/CSharpRepl/pull/156 due to issue https://github.com/waf/CSharpRepl/issues/148.

**Comment by waf** [comment]
See failing test case `ObjectInitialization_CompletionDoesNotInterfere` (currently commented out) for a repro.

**Comment by kindermannhubert** [comment]
The test is passing but real usage does not.

**Comment by kindermannhubert** [comment]
The issue was fixed for
`new { i = 0 }`
but not for
`new { i= 0 }`
