### ISSUE TITLE
.NET 7 is required?

### ISSUE THREAD

**Issue by marcinjahn** [waf/CSharpRepl#206]
### Version

none

### What happened?

The `README.md` says that csharprepl is a .NET 6.0 tool, however, when I try to install it (on Fedora 37), I get:

```
/tmp/c69af978-71cb-4df1-8275-a6a7781dd436/restore.csproj : error NU1202: Package CSharpRepl 0.5.1 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package CSharpRepl 0.5.1 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
The tool package could not be restored.
Tool 'csharprepl' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

It seems that .NET 7 is actually a requirement?

**Comment by kindermannhubert** [comment]
Yes, it was upgraded with #189. I've updated the README.md.
Thanks!

**Comment by kindermannhubert** [comment]
Don't take my word for granted, but I believe that currently the runtime of csharprepl tool and execution runtime of the scripts are the same. Execution of scripts is in the same process as csharprepl tool.
As I already mentioned in https://github.com/waf/CSharpRepl/issues/197#issuecomment-1399224412 it would be beneficial to move execution out of the main process.
