### ISSUE TITLE
Installation problem NU1202

### ISSUE THREAD

**Issue by llandi** [waf/CSharpRepl#211]
### Version

0.5.1

### What happened?

Trying to install the tool (on Windows 11 with SDK 7.0.1) it all fails with the following error:
C:\Users\lucal\AppData\Local\Temp\f4efd9a6-1b19-4f04-936f-4ed48a87b4bc\restore.csproj : error NU1202: The CSha package
rpRepl 0.4.0 is not compatible with net70 (.NETFramework,Version=v7.0)/any. The CSharpRepl 0.4.0 package supports: net6
.0 (.NETCoreApp,Version=v6.0)/any
The tool package could not be restored.
The 'csharprepl' tool could not be installed. The causes of this error are as follows:

* You are trying to install an older version and did not use the --version option to specify the version.
* A package with this name was found, but it does not match a .NET tool.
* The requested NuGet feed cannot be accessed, possibly due to an internet connection issue.
* The instrument name was typed incorrectly.
....

**Comment by kindermannhubert** [comment]
Interesting that version 0.4.0 of CSharpRepl is present in the provided error. 
0.4.0 used .NET 6.0.
0.5.1 uses .NET 7.0.

**Comment by llandi** [comment]
Yes you are right... in the various tests I also tried to install the old
0.4.0 one with --version parameter

Luca


Il giorno mer 4 gen 2023 alle ore 17:42 Hubert Kindermann <
***@***.***> ha scritto:

**Comment by kindermannhubert** [comment]
So, is this solved for you? Does version 0.5.1 work as expected?

**Comment by llandi** [comment]
Unfortunately no. I'm still not quite expert in the .NET Core world and
above all in having 5 or six different .NET SDKs installed on my PC. As
soon as I can I will try to recompile everything with VS2022 and not rely
on the precompiled binary taken from the net.

regards,
Luca

Il giorno mer 4 gen 2023 alle ore 20:50 Hubert Kindermann <
***@***.***> ha scritto:

**Comment by waf** [comment]
I'm going to close this out, because it sounds like there's some confusion on the installed .NET version as well as the installed csharprepl version. Feel free to reopen this if there's still something to be done here!
