### ISSUE TITLE
Usage of Spectre.Console.Table for enumerable objects formatting

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#225]
### Feature Description

When #223 is done.

**Comment by kindermannhubert** [comment]
New formatting will be cool! @waf 

Examples;
![image](https://user-images.githubusercontent.com/11704036/224555097-ee64c2f5-9ee8-49c4-94f3-4167b6276087.png)

(simple output):
![image](https://user-images.githubusercontent.com/11704036/224555213-3d52d3b2-3239-43af-8c06-93a62828bfa4.png)

(detailed output):
![image](https://user-images.githubusercontent.com/11704036/224555241-47df9c19-dce8-40bf-b497-6463d53dac63.png)

![image](https://user-images.githubusercontent.com/11704036/224554914-f3959e3c-0824-4960-94cb-02814a398c6e.png)

(simple output):
![image](https://user-images.githubusercontent.com/11704036/224554970-3b0938c9-4e85-4f23-aa38-59af78fc58cd.png)

(detailed output):
![image](https://user-images.githubusercontent.com/11704036/224555009-6a69491f-218d-42c6-b529-7c87961025ee.png)

**Comment by waf** [comment]
@kindermannhubert this looks great! love the syntax highlighting and tables.
