### ISSUE TITLE
Ability to customize the prompt

### ISSUE THREAD

**Issue by waf** [waf/CSharpRepl#24]
### Feature Description

Right now, the prompt is a simple `>` sign. It'd be nice to support customization of this prompt, either via a command line flag, an environment variable, or both. It should probably support ansi escape sequences for foreground/background colors.

The design of this could conflict with https://github.com/waf/CSharpRepl/issues/23

**Comment by kindermannhubert** [comment]
Could be customized in config (https://github.com/waf/CSharpRepl/issues/48).
