### ISSUE TITLE
Installation Issue - Wont run on Git Bash (MINGW64) on windows 10

### ISSUE THREAD

**Issue by paulfarr0w** [waf/CSharpRepl#240]
### Version

0.5.1

### What happened?

Wont start in Git Bash (MINGW64) command window on windows 10.
![csharpreplIssue](https://user-images.githubusercontent.com/13617995/228907887-47dd4fea-561c-4314-b99c-080a5f7ad23d.PNG)

**Comment by waf** [comment]
Git bash / mingw isn't a supported platform, but I would still expect this to work! What Windows version and mingw version are you using?

**Comment by waf** [comment]
Closing this as it's not supported. Contributions welcome if someone's interested in getting this working in mingw.
