### ISSUE TITLE
The documentation URL opened is wrong for locales not supported by microsoft.com

### ISSUE THREAD

**Issue by MrBogomips** [waf/CSharpRepl#241]
### Version

0.5.1

### What happened?

Issuing `F1` on `Console.Write("…")` the link generated is: https://learn.microsoft.com/en-us/en-IT/dotnet/api/System.Console.Write

The "en-us/en-IT" smells to me.

The link https://learn.microsoft.com/en-us/dotnet/api/System.Console.Write should be the correct one.

**Comment by waf** [comment]
Looked into this. The URL we generate is https://learn.microsoft.com/en-IT/dotnet/api/System.Console.Write (where `en-IT` comes directly from the local computer's `CultureInfo.CurrentCulture`), but I guess Microsoft's site doesn't support that locale. In my opinion it's a bug in their redirection logic that they redirect to `https://learn.microsoft.com/en-us/en-IT/dotnet/api/System.Console.Write`.

I've opened https://github.com/dotnet/dotnet-api-docs/issues/9000 on the dotnet docs repo. Ideally it's fixed there, but if not we can always add some handling on our side (e.g. we could unconditionally generate `en-us` if the locale is `en-XX` or something similar).

**Comment by waf** [comment]
Closing this, as soon as the linked bug is fixed, this issue will be fixed with no effort on our part.

**Comment by John0King** [comment]
Has this been fixed?  I think  the correct rule for microsoft.com's  cultures logic is that to drop the culture part from the url :
eg. 
```
https://learn.microsoft.com/{culture}/dotnet/api/system.console.write?view=net-7.0
=>
https://learn.microsoft.com/dotnet/api/system.console.write?view=net-7.0

```
