### ISSUE TITLE
IntelliSense ignores .csx

### ISSUE THREAD

**Issue by Emik03** [waf/CSharpRepl#248]
### Version

0.5.1

### What happened?

# Expected:
When you manually add code, IntelliSense works.

![image](https://user-images.githubusercontent.com/14614115/235346104-a78ec3e8-3dc3-4ee5-8d2a-293ebc3f8d48.png)

# Actual:
When you pass a `.csx` file containing functions or classes, IntelliSense ignores its existence.

![image](https://user-images.githubusercontent.com/14614115/235346063-f51e3f54-b632-4a58-a599-41d98455cc72.png)

Despite that, it can still be successfully called.

![image](https://user-images.githubusercontent.com/14614115/235346084-5719a52e-90b7-4a6a-b073-6e4f329daaca.png)

**Comment by waf** [comment]
This worked in v0.3.5, but broke in v0.4, and was apparently not covered by tests.

It was broken as part of the fix to https://github.com/waf/CSharpRepl/issues/140.

Possibly a fix is to pass `#load myFile.csx" to the script runner (which executed the script), but actually read the file and pass the contents to the roslyn workspace (which controls intellisense).

**Comment by Emik03** [comment]
Unfortunately, that workaround doesn't appear to work, unless I misunderstood you.

![image](https://user-images.githubusercontent.com/14614115/236701772-c93793db-bbe5-472a-8f20-5dac59a185e5.png)

Once again though, the function can be called just fine as this only affects IntelliSense.

![image](https://user-images.githubusercontent.com/14614115/236701803-bb85b27d-3a63-4339-8762-ab4105e81e69.png)

**Comment by waf** [comment]
Hey @Emik03, sorry, my comment was referring to a technical fix. You're right that this is broken in 0.5.1 and will require a bugfix. Thanks for reporting it!

**Comment by Emik03** [comment]
Ah alright, my bad. No problem!

**Comment by waf** [comment]
This is now available in v0.6 -- run `dotnet tool update --global csharprepl` to update to the newest version. Thanks again!

**Comment by Emik03** [comment]
Works beautifully, thank you so much for such an awesome tool!

![image](https://github.com/waf/CSharpRepl/assets/14614115/f0e00521-9a2b-47c5-aa09-d198e9d97d91)
