### ISSUE TITLE
NET 6 Preview Support

### ISSUE THREAD

**Issue by realivanjx** [waf/CSharpRepl#25]
### Feature Description

I recently reinstalled my vs installation and just noticed that it also removed my net5 installation. I think it would be good to support net6 preview versions too. Thanks.
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      6.0.0-preview.6.21352.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64
```

**Comment by waf** [comment]
Thanks for reporting! I agree this should work. You get this during installation, right? Or is it when launching csharprepl itself?

**Comment by waf** [comment]
@realivanjx Does the following work for you?

```
csharprepl --roll-forward LatestMajor
```

[As documented here](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#precedence). If that works, I can look at making this the default.

**Comment by realivanjx** [comment]
not sure if i can test it again without uninstalling net 5 first. i will try when i can.

**Comment by jjavierdguezas** [comment]
> @realivanjx Does the following work for you?
> 
> ```
> csharprepl --roll-forward LatestMajor
> ```
> 
> [As documented here](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#precedence). If that works, I can look at making this the default.

@waf @realivanjx I tried it in a fresh Windows Sandbox session and `csharprepl --roll-forward LatestMajor` worked

![image](https://user-images.githubusercontent.com/13673443/128321329-495166ce-64dc-4bc7-92d5-615592b65c75.png)

**Comment by NickStavrou-Net** [comment]
Hello am facing this issue when try to install csharprepl. The solution mentioned above didn't help.
Any ideas how to overcome this issue?
![image](https://user-images.githubusercontent.com/54780858/139929299-3b6fd3f3-6864-4a22-8163-17ab41fa060b.png)

list of sdks installed
![image](https://user-images.githubusercontent.com/54780858/139929524-3dd89c32-2654-4df9-8844-26e9c251983c.png)

**Comment by waf** [comment]
@NickStavrou-Net that URL (`http://packagesource/`) looks odd. Do you have a nuget.config file somewhere that is overridding the normal nuget URL? I believe it should download from `https://api.nuget.org` (at least it does on my machine).

**Comment by NickStavrou-Net** [comment]
@waf i found a solution and installed it. 
Went to nuget.org and copied the URL from there which had the version specified.
![image](https://user-images.githubusercontent.com/54780858/140173960-be11bd9a-698d-4df0-b65e-af37a517b2da.png)

I really needed your tool as it is way faster than creating console apps all the time for tests.
Thanks for your time.
