### ISSUE TITLE
Unable to reference packages with implicit PATCH/MINOR versioning

### ISSUE THREAD

**Issue by Emik03** [waf/CSharpRepl#251]
### Version

0.5.1

### Problem

A package that doesn't specify `MINOR` or `PATCH` in [nuget](https://www.nuget.org/) (such as my package [`Emik.Results`](https://www.nuget.org/packages/Emik.Results/1.2)) will not be able to be referenced properly.

![image](https://user-images.githubusercontent.com/14614115/236788924-f71e101b-5683-4913-ad53-c3b9ac503a8d.png)

If we look into the folder it talks about, we see that it normalizes the versioning to `Emik.Results.1.2.0`, failing to fallback to `Emik.Results.1.2`.

![image](https://user-images.githubusercontent.com/14614115/236789788-952fe5c1-1bc4-461a-9b11-bc53626c9ca5.png)

According to the [official spec](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#where-nugetversion-diverges-from-semantic-versioning), you are allowed to implicitly define `MINOR` and `PATCH`, as well as explicitly define `REVISION` even when zero.
> 2. `NuGetVersion` only requires the major segment to be defined. All others are optional, and are equivalent to zero. This means that `1`, `1.0`, `1.0.0`, and `1.0.0.0` are all accepted and equal.

### Workaround

Creating a symlink `ln -s Emik.Results.1.2 Emik.Results.1.2.0` resolves this issue.

![image](https://user-images.githubusercontent.com/14614115/236790284-ac5e148f-d430-4b87-9732-188d5ecb6c85.png)

![image](https://user-images.githubusercontent.com/14614115/236790424-17c3b902-6c59-4d3c-96aa-64e8af294311.png)

**Comment by waf** [comment]
Thanks for this! Opened #252 which solves this. Also adds Emik.Results to our test cases. Nice library, result types are 🔥

**Comment by waf** [comment]
This is now available in v0.6 -- run `dotnet tool update --global csharprepl` to update to the newest version. Thanks again!
