### ISSUE TITLE
Cannot type in characters requiring modifier keys

### ISSUE THREAD

**Issue by sidewinder94** [waf/CSharpRepl#260]
### Version

0.6.1

### What happened?

On certain keyboard layouts, to type certain characters (critical examples : `{`, `}`, `[`, `]`) one needs to use a combination of keys (e.g. on an AZERTY keyboard `AltGr` + `4` or `Ctrl` + `Alt` + `4`).

Right now, when using that combination nothing happens.

Whereas if I switch my keyboard to a QWERTY layout, I only need `MAJ` + `[`, and in this case, the character `{` is printed successfully

Quite obviously, changing keyboard layouts frequently is not desirable.

**Comment by ErikWil** [comment]
I can confirm that this is also the case with a QWERTY keyboard with Norwegian layout (Windows 10). In this case you need to type <kbd>AltGr</kbd><kbd>7</kbd> (={), <kbd>AltGr</kbd><kbd>8</kbd> (=[), <kbd>AltGr</kbd><kbd>9</kbd> (=])

**Comment by bramborman** [comment]
Also got hit by the same issue using Czech QWERTZ keyboard with similar key combinations.

Downgrading to 0.5.1 solved the issue.

**Comment by microdee** [comment]
I have same problem with German and Hungarian, I have a feeling that every keyboard layout but the English one has AltGr characters.

**Comment by waf** [comment]
Hey all, thanks for reporting this. I'll look into this as a top priority for the next release.

**Comment by waf** [comment]
Thanks for everyone's patience on this. I've just release version 0.6.2 that solves the issue. You can update by running `dotnet tool update -g csharprepl` and please let me know if you run into any issues.
