### ISSUE TITLE
Fails to encode non-ASCII characters spam

### ISSUE THREAD

**Issue by Emik03** [waf/CSharpRepl#261]
### Version

0.6.1

## Problem

When holding down non-ASCII keys (such as `ä`) or holding paste on emojis/unicode characters (such as `❌`), the encoder struggles.

The output from `csharprepl --trace` is unfortunately unhelpful; Nothing is logged after initialization.

This isn't a huge burden, but I would be thankful if you do fix it, thanks!

## Example

![2023-05-19_15 08 23](https://github.com/waf/CSharpRepl/assets/14614115/6d5508f1-64c2-4572-9210-f20ad0e1a3a1)

**Comment by waf** [comment]
Hi @Emik03, thank you for the bug report and research. I'm not currently able to reproduce this. Would you mind sharing which terminal and OS you're using?

Also, does this still happen if start CSharpRepl with the `--useUnicode true` flag? I'm guessing it does still happen as that doesn't change how bytes are sent to the terminal, but just looking to narrow down differences between my setup and yours. Thanks!

**Comment by Emik03** [comment]
It indeed does happen regardless of the value set in `useUnicode`.
I can still replicate this after removing `config.rsp` and `prompt-history`, then launching it with no arguments.

OS: Pop!_OS 22.04 LTS x86_64
Shell: bash 5.1.16
DE: GNOME 42.5
Terminal: gnome-terminal
Layout: Swedish (no dead keys)

**Comment by Emik03** [comment]
I suspect it might be to do with how Windows uses UTF16 everywhere, which includes command-line interfaces, meanwhile Linux uses UTF8.

**Comment by Emik03** [comment]
Update: This is definitely an issue with [`PrettyPrompt`](https://github.com/waf/PrettyPrompt) as I was able to use the example code and reproduce this exact behavior. The higher the key repeat speed, the easier it breaks.
![image](https://github.com/waf/CSharpRepl/assets/14614115/aab150a5-753d-43e1-b3cf-3bf02d40967d)

**Comment by waf** [comment]
Nice, thanks for that. I'm able to reproduce this on Windows Terminal with Ubuntu on WSL. Cannot reproduce at all on Windows Terminal on Windows.

**Comment by waf** [comment]
Narrowed this down to an issue in the core .NET libs. https://github.com/dotnet/runtime/issues/88343

In the meantime, I think we can do a workaround to remove a call to `Console.CursorTop` which is ultimately causing the issue.

**Comment by waf** [comment]
I've implemented this in the underlying PrettyPrompt library, when we upgrade that library CSharpRepl will get this fixed. Thanks for the report!
