### ISSUE TITLE
Problem with curly brace or square bracket

### ISSUE THREAD

**Issue by nikbra** [waf/CSharpRepl#266]
### Version

0.6.1

### What happened?

Hi

Did see that this is closed (https://github.com/waf/CSharpRepl/issues/265)

I have that problem. Alt-Gr works everywhere else for me in Windows 11, but unfortunately not here.

So is there something I can do or setup somewhere ?

I'm going to test on another computer as well.

//Regards Niklas

**Comment by nikbra** [comment]
I have tested on second computer with the same version. And it does not work for me

**Comment by fortender** [comment]
I can confirm. No character that depends on Alt-Gr can be typed. I am using a german keyboard layout.

**Comment by waf** [comment]
Thanks for raising this. I've just release version 0.6.2 that solves this issue. You can update by running `dotnet tool update -g csharprepl` and please let me know if you run into any issues.
