### ISSUE TITLE
Caret jumping around while typing

### ISSUE THREAD

**Issue by malino-dev** [waf/CSharpRepl#267]
### Version

0.6.1

### What happened?

When I'm typing in stuff (in this case Math.Floor), then my caret is resetting itsself to the start of the line sometimes for no reason.

**Comment by waf** [comment]
Hi @zondaken, thanks for the report. Could you please help me reproduce this by providing the following?

- What OS and Terminal are you using?
- Does it also happen in Windows Terminal?
- What is the exact string you're typing that cause the jump?

Thanks!

**Comment by zondaken** [comment]
- Win 10 and Command Prompt
- In both CMD and PowerShell
- It happens with "new int[] { }.Aggregate" and happens exactly when I type the dot. But only in non-maximized mode as I said.

**Comment by kindermannhubert** [comment]
Could you try the latest version and paste gifs (can be recorded with e.g. ShareX) of the described behavior?
I'm not able to reproduce it.

cmd:
![cmd_WBCE7YKBAI](https://github.com/waf/CSharpRepl/assets/11704036/afd31284-24c2-4835-84bf-c909f58ca543)

Windows Terminal:
![WindowsTerminal_bf8wh6HD3g](https://github.com/waf/CSharpRepl/assets/11704036/1c892b15-5751-4297-9fcc-0584b869bb59)
