### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by jkone27** [waf/CSharpRepl#270]
### Feature Description

F# already has a native REPL as dotnet fsi, but this C# repl is amazing in colorization and intellisense.

would it be possible to somehow plug into also F# or maybe via this? https://github.com/jonsequitur/dotnet-repl. provide support for F# language as well?

Cheers! really nice REPL!

**Comment by waf** [comment]
Thanks! The CSharpRepl project by itself is very specific to C#, but the underlying [PrettyPrompt](https://github.com/waf/PrettyPrompt) companion library (developed alongside CSharpRepl) actually has all the "user experience" features of the REPL like terminal syntax highlighting, intellisense menus, overload menus, etc. So CSharpRepl simply configures PrettyPrompt library with C#-specific functionality.

That's a long way of saying that if someone wanted to build a similar F# REPL, they could build it on top of PrettyPrompt which is itself language-agnostic. I don't think CSharpRepl will add support for F# directly, but it's been developed in such a way that F# could benefit by building on top of PrettyPrompt.
