### ISSUE TITLE
Consider using `Dumpify` for dumping objects

### ISSUE THREAD

**Issue by MoaidHathot** [waf/CSharpRepl#286]
### Feature Description

Although `CSharpRepl` has the ability to "dump" objects into the Console, it can't do that for every type of object.
[`Dumpify`](https://github.com/MoaidHathot/Dumpify) is a relatively new package, that uses `Spectre.Console` as well, to dump and render any type of .NET object into the console, but it support more features and is very customizable.

For example, the following code 
```csharp
public class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

var moaid = new Person { FirstName = "Moaid", LastName = "Hathot" };
```
Outupts: 
![image](https://github.com/waf/CSharpRepl/assets/8770486/a1ab0402-dc8f-4939-884b-8c1edefd5a4a)

While using `Dumpify` the same code outptus:
![image](https://github.com/waf/CSharpRepl/assets/8770486/37c7d241-0b32-4259-90fe-66d5cf99f310)

Another example:
```csharp
var map = new Dictionary<string, person>
  {
      ["Moaid"] = new person { FirstName = "Moaid", LastName = "Hathot" },
      ["Haneeni"] = new person { FirstName = "Haneeni", LastName = "Shibli" },
  };
```
`CSharpRepl` outputs:
![image](https://github.com/waf/CSharpRepl/assets/8770486/505ac83d-151a-44bb-8d4a-f504b012b75e)

While `Dumpify` outputs:
![image](https://github.com/waf/CSharpRepl/assets/8770486/f9e19607-bb45-4dd6-bb1f-1ddbba008480)

The colors are configurable, so `CSharpRepl` can change them to maintain the same color scheme. The only missing abilities that I currently see:
* Writing the property types in a separate column. While `Dumpify` writes type names at the top of tables , there is work to add a column for the types (configuration).
* Limiting the length of array/collections to show only part of the items. This is also easy to implement, and can get a priority bump if needed.

**Comment by waf** [comment]
Nice, Dumpify looks good, we should definitely consider it.

@kindermannhubert any thoughts on this? You have the most experience with our current rich object formatting.

**Comment by MoaidHathot** [comment]
@kindermannhubert, that is ok, no offense taken :)

Regarding dumping types such as `typeof(int).Dump()`, the current output from `Dumpify` is by definition, since otherwise the outputted table is very big, and in most cases it will dump too much information. This of course can be changed if the community prefers otherwise, but `Dumpify` supports dumping `System.Reflection` types such as `System.Type`'s members, for example:
![image](https://github.com/waf/CSharpRepl/assets/8770486/8f627af2-fe3b-4c23-8e59-a223efb92895)

Btw, do you handle circular references with the Tree formatting? I still get only `.person` with `ctrl+enter`
![image](https://github.com/waf/CSharpRepl/assets/8770486/8266e6e0-cd88-4a3c-a89c-5e8c0beef476)




Regardless of this discussion, `CSharpRepl` is awesome, and I use it quit a lot, thanks! 
Good job and keep up the awesome work :)

**Comment by waf** [comment]
Closing this. If developers do want to use Dumpify with CSharpRepl it's a quick `#r "nuget: Dumpify"` away.

I agree that this is a library the .NET ecosystem sorely needs. Nice work on it so far.
