### ISSUE TITLE
Could not load file or assembly NuGet.Common

### ISSUE THREAD

**Issue by sergiojrdotnet** [waf/CSharpRepl#294]
### Version

0.6.5

### What happened?

![image](https://github.com/waf/CSharpRepl/assets/72770006/e89fbae9-f7fd-4e1f-bdf9-914e18937d0a)

**Comment by vincentkam** [comment]
Fwiw I saw something similar on my Mac (Apple silicon) and was able to resolve it by uninstalling `dotnet` and installing `dotnet-sdk` instead.

**Comment by waf** [comment]
Thanks for opening this, and for the workaround. This is a persistent issue that's been plaguing a lot of roslyn-based projects. I'll see if I can figure out a permanent fix, or at least a workaround.

**Comment by sergiojrdotnet** [comment]
@waf do you have any ETA on this one?

**Comment by sergiojrdotnet** [comment]
> Thanks for opening this, and for the workaround. This is a persistent issue that's been plaguing a lot of roslyn-based projects. I'll see if I can figure out a permanent fix, or at least a workaround.

@waf do you have any ETA on this one?

**Comment by sergiojrdotnet** [comment]
The actual code on main branch is working fine

**Comment by waf** [comment]
Thanks for checking @sergiojrdotnet! I reworked how the nuget libs were loaded due to this bug report, as part of the .NET 8 upgrade (https://github.com/waf/CSharpRepl/pull/320). I had suspected that it would fix this issue, but had not yet had time to verify it. Appreciate the check.
