### ISSUE TITLE
Nuget.org Project Site or Source Repo reference

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [waf/CSharpRepl#3]
I assume that https://www.nuget.org/packages/CSharpRepl/ is the package for the tool. The **Project Site** and **Source repository**  links refer to https://github.com/waf/PrettyPrompt.

**Comment by waf** [comment]
Thanks for the heads up! Appreciate you taking the time to report this. 👍

**Comment by waf** [comment]
I'll roll out a new version soon, with this fixed, thanks again!

**Comment by waf** [comment]
This has shipped in v0.2.1, cheers!
