### ISSUE TITLE
Unable to load projects "#r ...csproj"

### ISSUE THREAD

**Issue by onionhammer** [waf/CSharpRepl#31]
### Version

C# REPL 0.3.0

### What happened?

When running on Mac OS, including a project simply shows a 'no such file or directory' error

```C#
> #r "./Model/Model.csproj"
Building ./Model/Model.csproj
No such file or directory
```

In bash

```sh
> which dotnet
/usr/local/share/dotnet/dotnet
```

**Comment by waf** [comment]
@onionhammer thanks for taking the time to report the issue. Can you please try upgrading to release 0.3.1 (I just released it moments ago)? This should resolve your issue.

You can upgrade via `dotnet tool update -g csharprepl`

This issue was fixed in https://github.com/waf/CSharpRepl/pull/28,

**Comment by onionhammer** [comment]
@waf Works perfectly now, thanks for the quick fix!

Loving this project btw - would be awesome if loading #r project worked in dotnet interactive notebooks.. have you thought about adapting this as a dotnet interactive kernel ( I have no idea how much effort that would be and I'm not trying to put that on you just asking 😇 )

**Comment by waf** [comment]
Thanks! Glad you're enjoying using it 😃 

Ah, that's a neat idea. It should be doable. CSharpRepl isn't tied to the command line; the command line just happens to be the current renderer. It might not be too difficult to repurpose it as a kernel (though I've never written a Jupyter kernel before, so I'm probably underestimating the effort!).

From a quick look, CSharpRepl's [ReplServices](https://github.com/waf/CSharpRepl/blob/main/CSharpRepl.Services/Roslyn/RoslynServices.cs) implementation looks quite similar to [dotnet interactive's C# kernel](https://github.com/dotnet/interactive/blob/main/src/Microsoft.DotNet.Interactive.CSharp/CSharpKernel.cs).

**Comment by onionhammer** [comment]
To me dotnet interactive's inability to load csproj's is its single biggest drawback, and I suspect biggest reason it's not more widely used.
