### ISSUE TITLE
Upgrade to .NET 8

### ISSUE THREAD

**Issue by Emik03** [waf/CSharpRepl#319]
### Feature Description

.NET 8 has just now been [stabilized](https://dotnet.microsoft.com/en-us/download/dotnet/8.0), and 7 is now marked as ["Maintainance"](https://dotnet.microsoft.com/en-us/download/dotnet) (approaching end-of-life).

Not to be mistaken with #281, since this applies for the application itself.

**Comment by waf** [comment]
Done! Cheers.
