### ISSUE TITLE
DateTime.ToString formatting display error

### ISSUE THREAD

**Issue by ilyfairy** [waf/CSharpRepl#326]
### Version

C# REPL 0.6.6+ba21d409af4dce77f8be07f6a61cdb24cd19bb29

### What happened?

as the picture shows

![image](https://github.com/waf/CSharpRepl/assets/52264192/196228bd-cb11-44ed-9073-46002c5c460c)

**Comment by kindermannhubert** [comment]
Interesting that you have the cursor behind the `)` character. These are completions for specific DateTime formats and should be provided inside the format string.

Unfortunately, I wasn't able to reproduce the issue. Looks like this for me:
![WindowsTerminal_9iCMpzYTDV](https://github.com/waf/CSharpRepl/assets/11704036/bf5a397e-4d62-47e4-a638-b11da3393e28)

**Comment by ilyfairy** [comment]
I tried it recently and it became normal again.
