### ISSUE TITLE
Create a CHANGELOG.md

### ISSUE THREAD

**Issue by jjavierdguezas** [waf/CSharpRepl#35]
### Feature Description

Create a `CHANGELOG.md` file to easily know what the new features and bug fixes are in each new release (also you can use github releases)

**Comment by waf** [comment]
Thanks! Yeah, I've just been putting change notes in the commit that creates the new version. This really should be scripted and autogenerated from the commit log...

**Comment by jjavierdguezas** [comment]
https://github.com/orhun/git-cliff 👀

**Comment by waf** [comment]
Done! https://github.com/waf/CSharpRepl/blob/main/CHANGELOG.md

As part of this, we now have scripted releases, push a tag like v0.3.4 and Github Actions will publish to nuget.

Thanks for the raising the issue!
