### ISSUE TITLE
How can i exit from a endless loop on windows ?

### ISSUE THREAD

**Issue by wilari932** [waf/CSharpRepl#38]
### Version

REPL 0.3.3

###I tried to just run some endless code but my window don't allow me to exit ?

![image](https://user-images.githubusercontent.com/33053518/132845953-990180d3-fbac-4c05-a0f1-1f495d5e339b.png)

**Comment by waf** [comment]
Thanks for reporting. There's some initial support for this (there's a cancellation token created from the Ctrl-C command, and passed through to the Roslyn APIs), but I there's an underlying blocker in the Roslyn Scripting APIs: they don't support cancellation. You'll see the same thing in Visual Studio's "C# Interactive" window.

The only workaround supported today is to close the window, but it's definitely not ideal. Another workaround is to not type that 😄 

There's two potential ways we could fix this, but they're not straightforward:

- We could play around with introducing some `Thread.Abort()` support to kill the execution. No telling if that would cause more problems down the line.
- Provide some way to kill all of csharprepl (e.g. detect if something's still running ~2 seconds after cancellation was requested)

**Comment by waf** [comment]
This has been fixed in v0.3.5. Thanks!

I chose the second approach (exit csharprepl) -- it's safer, and it at least doesn't block the terminal and trap the user.
