### ISSUE TITLE
Crashing the program...

### ISSUE THREAD

**Issue by IBIT-ZEE** [waf/CSharpRepl#4]
to **crash** the program:

in the console just type "`c1`"

![c#REPL-err](https://user-images.githubusercontent.com/3254076/120329732-0d83b700-c2e4-11eb-9f0f-9e515b92426e.png)

**Comment by waf** [comment]
well, that's a dead simple repro. I'll take a look, thanks!

**Comment by IBIT-ZEE** [comment]
;-) 
en route to be the best C# REPL in the Universe... 
hell... in the Multiverse too!!!
it's my favorite now!!!

**Comment by waf** [comment]
Thanks, I'm glad you're liking it, and thanks for helping to improve it! The fix has shipped now in v0.2.1, you can update via:

```
dotnet tool update -g csharprepl
```
