### ISSUE TITLE
"Package contains multiple .nuspec files" when referencing nuget packages on linux

### ISSUE THREAD

**Issue by webczat** [waf/CSharpRepl#52]
### Version

0.3.5

### What happened?

I am trying to reference nuget packages on linux but often get errors like "Package contains multiple .nuspec files" or sometimes it seems to work but doesn't end up in adding references, like for "Microsoft.EntityFrameworkCore.SQLite".
As an example, if I run csharprepl and try to install "Microsoft.EntityFrameworkCore" it goes fine, then "Microsoft.CodeAnalysis.CSharp.Scripting" fails with the above error. I then have to completely remove cache to proceed. Also restarting csharprepl and trying to reference Microsoft.EntityFrameworkCore that worked before suddenly doesn't and displays the above error.

**Comment by kindermannhubert** [comment]
Reproduction steps:

1. Clear package's cache (`.csharprepl\packages`).
2. `#r "nuget: Microsoft.EntityFrameworkCore"`
3. `#r "nuget: Microsoft.CodeAnalysis.CSharp.Scripting"`

The problem emerges on systems with case-sensitive file system.
There can be multiple nuspec files differing only in name casing in the package folder.
Not sure why this happens (I suspect there is a bug in NuGet.PackageManagement).

I've added a patch (#109) for this issue that detects this situation and deletes duplicate nuspec files.
