### ISSUE TITLE
Allow visual dump of Objects

### ISSUE THREAD

**Issue by NickAcPT** [waf/CSharpRepl#55]
### Feature Description

For a while now, I've been looking at free alternatives to LINQPad and CSharpRepl has always stood out to me for being something very flexible (along with frequent updates), and a thing that I noticed while using this tool recently is the lack of "visually" inspect any arbitrary object, similar to what LINQPad and SharpLab provide.

Below are some examples of what I'm talking about.

<details>
<summary>Example images</summary>

![Dump Example 1](https://www.linqpad.net/images/maincodescratchpad.png)
![Dump Example 2](https://www.linqpad.net/images/thebigdump.png)

</details>

Obviously that there are certain things that probably cannot be accomplished inside a terminal, but anything is better than nothing.

**Comment by NickAcPT** [comment]
@waf Sorry to be bumping an issue that's a bit old. Recently picked up csharprepl again and hit this again.
There's no way to visually inspect the objects other than the ToString method and poking at them manually.

While that isn't implemented, is there some kind of workaround that one can use to achieve something similar?

**Comment by kindermannhubert** [comment]
Do you know about 'Ctrl+Enter' detailed output?
It's not interactive in any way but provides more insight into the result. Although I'd like to improve it in the future.

**Comment by NickAcPT** [comment]
> Do you know about 'Ctrl+Enter' detailed output? It's not interactive in any way but provides more insight into the result. Although I'd like to improve it in the future.

Oh shoot, I did not! I really did miss it, thanks for bringing it up! I'll leave this issue opened just in case something else can be implemented

**Comment by kindermannhubert** [comment]
Should be solved when #226 is done.

**Comment by waf** [comment]
We now have a much nicer visual dump of objects (still triggered via Ctrl + Enter), courtesy of @kindermannhubert. I think we can close this issue now.

It looks like this:

![image](https://github.com/waf/CSharpRepl/assets/97195/edad8f70-f518-4930-9774-6b7ca91be949)
