### ISSUE TITLE
PrettyPrinter crash

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#79]
### Version

last

### What happened?

Just enter `Console.OutputEncoding`:
![image](https://user-images.githubusercontent.com/11704036/156940139-c4faacea-c233-4014-ba06-a85b356b188f.png)

**Comment by waf** [comment]
I believe the root cause of this is https://github.com/dotnet/roslyn/issues/51548

Console.OutputEncoding is of type `System.Text.UTF8Encoding+UTF8EncodingSealed`, which contains a ReadOnlySpan<byte> (which is a ref struct).

**Comment by waf** [comment]
A work around is implemented in #133 -- we'll just return the ToString implementation when the underlying formatter throws an exception. When the above issue is resolved it will just naturally start taking the normal "pretty print" output.

**Comment by kindermannhubert** [comment]
This will be fixed correctly when #223 is done.

Current output:
![image](https://user-images.githubusercontent.com/11704036/222968047-0ab192b1-4743-4a14-8819-71219313f1a0.png)


New output:
![image](https://user-images.githubusercontent.com/11704036/222968061-e06f8eaa-2b6a-4cad-b8f3-9cf9a32f120d.png)
